-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 00:23:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rt20g
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rt20g` ;

-- -----------------------------------------------------
-- Schema rt20g
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rt20g` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `rt20g` ;

-- -----------------------------------------------------
-- Table `rt20g`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rt20g`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rt20g`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT ZEROFILL NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rt20g`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rt20g`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rt20g`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT ZEROFILL NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rt20g`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rt20g`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rt20g`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_petstore_idx` (`pst_id` ASC) VISIBLE,
  INDEX `fk_pet_customer1_idx` (`cus_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_petstore`
    FOREIGN KEY (`pst_id`)
    REFERENCES `rt20g`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_customer1`
    FOREIGN KEY (`cus_id`)
    REFERENCES `rt20g`.`customer` (`cus_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `rt20g`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `rt20g`;
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Claws and Paws', '123 Main St.', 'L.A.', 'CA', 090195341, 8185551234, 'clawspaws@aol.com', 'http://www.clawspaws.com', 50000, 'notes1');
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Furry Friends', '1435 Chase Dr.', 'Chicago', 'IL', 629959031, 8471234567, 'furryfriends@hotmail.com', 'http://www.furryfriends.com', 65000, 'notes2');
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Partners', '811 4th St.', 'NY', 'NY', 404852911, 2129877659, 'petparners@yahoo.com', 'http://www.petpartners.com', 87000, 'notes3');
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Palace', '18903 Tennessee St.', 'Tallahassee', 'FL', 202543781, 4049327818, 'petpalace@gmail.com', 'http://www.petpalace.com', 34000, 'notes4');
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Purrs and Gurrs', '751 Lois Lane', 'Phoenix', 'AZ', 943156321, 4809130015, 'purrsandgrrs@msn.com', 'http://www.purrsandgurrs.com', 97500, 'notes5');
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Smart ', '45 Freshfield Way', 'Freeport', 'MA', 850445890, 7819529818, 'petsmart@hotmail.com', 'http://www.petsmart.com', 75000, 'notes6');
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pets and Friends', '105 Hedgewick Way', 'Tyrone', 'VA', 480952891, 2054921199, 'petsandfriends@outlook.com', 'http://www.petsandfriends.com', 80000, 'notes7');
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Petco', '167 Whitcott Hill', 'Peachtree CIty', 'AL', 564738219, 5057819321, 'petco@gmail.com', 'http://www.petco.com', 90000, 'notes8');
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Hollywood Pets', '222 N Ocala Rd.', 'Gainesville', 'GA', 324390891, 7073456127, 'hollywoodpets@msn.com', 'http://www.hollywoodpets.com', 62500, 'notes9');
INSERT INTO `rt20g`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Furry Paws', '890 Middle Oval', 'Orlando', 'TN', 000036790, 1212989034, 'furrypaws@yahoo.com', 'http://www.furrypaws.com', 72500, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `rt20g`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `rt20g`;
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'BIlly', 'Bob', '502 Shady Dr.', 'Minneapolis', 'MN', 004011238, 6124567890, 'bbob@aol.com', 139.52, 987.61, 'notes1');
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Bobby', 'Sue', '19567 Rutherford Cir.', 'Charleston', 'WV', 016731278, 0167217890, 'sbobby@hotmail.com', 49.87, 1356.89, 'notes2');
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Stevie', 'Ray', '8624 Baldwin Dr.', 'Panama City Beach', 'FL', 850998123, 5059870191, 'sray@fsu.edu', 9.34, 567.45, 'notes3');
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Felicia', 'Fuller', '7831 Tempest Ln.', 'Sturgis', 'SD', 505298189, 7819828719, 'ffuller@msn.com', 1.40, 784.57, 'notes4');
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Victoria', 'Valis', '63178 Northshore Dr.', 'Laramie', 'WY', 707892431, 3039819019, 'vvalis@yahoo.com', 1189.31, 19456.89, 'notes5');
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Lillian', 'Tang', '678 Turner CLose Ln.', 'Boston', 'MA', 450902123, 7079819821, 'ltang@gmail.com', 100.90, 1234.56, 'notes6');
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Diego', 'Mendoza', '431 Manor Gardens', 'Las Vegas', 'NV', 890129183, 6780919281, 'dmendoza@gmail.com', 82.99, 678.99, 'notes7');
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Ronald', 'Tang', '345 Station Rd.', 'San Francisco', 'CA', 505938173, 8901902919, 'rtang@hotmail.com', 56.99, 564.23, 'notes8');
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'John', 'Doe', '89 Wentworth Dr.', 'Orlando ', 'FL', 1809281747, 1809281747, 'jdoe@fsu.edu', 45.78, 459.99, 'notes9');
INSERT INTO `rt20g`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Cali', 'Glover', '178 Warwick Rd.', 'Miami', 'FL', 4049329119, 4049329119, 'cglover@aol.com', 34.99, 789.99, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `rt20g`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `rt20g`;
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 5, 'Doberman', 'm', 350, 525, 52, 'black/tan', '2009-07-05', 'y', 'y', 'notes1');
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 6, 'Chiwawa', 'f', 175, 165, 78, 'white/brown', NULL, 'n', 'n', 'notes2');
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 7, 'American Bobtail', 'm', 195, 385, 67, 'black', '2011-09-12', 'y', 'y', 'notes3');
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, 9, 'American Longhair', 'f', 165, 275, 98, 'white', '2004-10-11', 'y', 'n', 'notes4');
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, NULL, 'British Shorthair', 'f', 155, 145, 45, 'grey', NULL, 'y', 'n', 'notes5');
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 1, 'Rose-Ringed Parrot', 'm', 18, 32, 34, 'green/yellow', '2010-06-12', 'y', 'y', 'notes6');
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 2, 'African Grey Parrot', 'm', 1295, 1800, 55, 'grey/blue', '2015-08-08', 'n', 'n', 'notes7');
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, NULL, 'Pitbull', 'f', 300, 495, 65, 'black/white', '2016-12-31', 'n', 'n', 'notes8');
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 3, 'Boa Constrictor', 'f', 450, 735, 78, 'grey/green', '2014-05-02', 'y', 'n', 'notes9');
INSERT INTO `rt20g`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, 4, 'Giraffe', 'f', 1735, 2495, 89, 'yellow and black', NULL, 'y', 'n', 'notes10');

COMMIT;

